name: tests

on:
  - push
  - pull_request

jobs:
  test:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        pytorch-version: [1.7, 1.8]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache installed requirements
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
    - name: Install tox and tox-gh-actions
      run: pip install tox==3.21.3 tox-gh-actions==2.4.0
    - name: Lint using flake8
      run: tox -e flake8
    - name: Run tests with tox
      env:
        PLATFORM: ${{ matrix.os }}
        PYTORCH: ${{ matrix.pytorch-version }}
        TEST_DEVICE: "cpu"
      run: |
        tox
    - name: Upload coverage.xml
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9' }}
      uses: actions/upload-artifact@v2
      with:
        name: tox-gh-actions-coverage
        path: coverage.xml
        if-no-files-found: error
    - name: Upload coverage.xml to codecov
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9' }}
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
